### ISSUE TITLE
Review of email bug reports (Marcel)

### ISSUE THREAD

**Issue by fczuardi** [fczuardi/calamarcopollo#33]
- [x] use m. URLS as a workaround for the partner's website redirection problems (#34)
- [x] urls with no date parameters, fixed with f260d716b804004ba992a8eb7a356554d47ef520
- [x] support for terminal names search (#38)
- [x] support for asking for roundtrips (#37)
- [x] investigate on the logs a reported new search that didnt replaced the previous one (#36)
  - "Quando fazemos uma segunda consulta de rota (após a resposta da primeira rota), ele retorna a mesma mensagem anterior (rota passada);"
  - couldnt find and couldnt reproduce
- [x] change the message on queries that the evaluation API don't support and inform the partner that we still need access to the full API and not only the one with fake results for just 2 cities (#35)
  - "Alguns casos a mensagem de resposta é negativa (não encontrou) mas exibe o link de redirecionamento, isso pode confundir o usuário."
